#!/bin/bash
# Program

# ODMONTOWANIE KARTY SD JESLI NADAL WIDOCZNA W SYSTEMIE
if df | grep -q '/mnt/sda1' # Sprawdzenie czy jest zamontowane
then
	sudo umount /mnt/sda1
	sudo rm -r /mnt/sda1
fi

# CZYSZCZENIE ZMIENNYCH
suma1_a=""
suma2_a=""
data_a=""
label_a=""
nazwa_folderu_a=""

# CZYTANIE FOLDERU GLOWNEGO NA ZDJECIA
#
sciezka="$(cat /home/pi/Desktop/Zgrywanie_SD/sciezka)"
#sciezka=$(cat /mnt/test/foto/do_edycji)

# TWORZENIE NAZWY FOLDERU NA PODSTAWIE LABELA KARTY I AKTUALNEJ DATY
label_a=`sudo lsblk -o LABEL /dev/sda1`
data_a=$(date +%Y-%m-%d_%H%M%S)
nazwa_folderu_a=${label_a}_${data_a}

# ZAMONTOWANIE KARTY SD
sudo mkdir /mnt/sda1
sudo mount /dev/sda1 /mnt/sda1

# SPRAWDZENIE NAZWY FOLDERU
echo $nazwa_folderu_a

# SZUKANIE ZDJEC W FOLDERACH I OKRESLENIE SUMY KONTROLNEJ
suma1_a=$(sudo find /mnt/sda1 -iname "*.*" -exec md5sum {} + | awk '{print $1}' | sort | md5sum)
echo "Zamontowano sda1"

#sudo mogrify -resize '1600x1200' /mnt/sdb1/*.*
#echo "Zmniejszono zdjecia"

# TWORZENIE FOLDERU TYMCZASOWEGO ZE ZDJECIAMI PRZENIESIONYMI Z KARTY
sudo sshpass -p '123qaz123qaz' ssh -o StrictHostKeyChecking=no zdjecia@192.168.0.108 mkdir -p temp_a </dev/null
echo "Utworzono tempa"

# WYSYLANIE ZDJEC DO FOLDERU TYMCZASOWEGO
sudo sshpass -p '123qaz123qaz' scp -o StrictHostKeyChecking=no -p $(find /mnt/sda1 -iname "*.*") zdjecia@192.168.0.108:temp_a </dev/null
echo "Wyslano zdjecia do tempa"

# OKRESLENIE SUMY KONTROLNEJ PRZENIESIONYCH ZDJEC
suma2_a=$(sudo sshpass -p '123qaz123qaz' ssh zdjecia@192.168.0.108 find temp_a -iname "*.*" -exec md5sum {} + | awk '{print $1}' | sort | md5sum) </dev/null

# WYSWIETLENIE SUM KONTROLNYCH
echo "Stworzono sume dla *ow w tempie"
echo "Sumy:"
echo $suma1_a
echo $suma2_a

# POROWNANIE SUM KONTROLNYCH W CELU SPRAWDZENIA POPRAWNOSCI SKOPIOWANIA ZDJEC Z KARTY
if df | grep -q '/dev/sda1'
then
	if [ "$suma1_a" = "$suma2_a" ]
	then
		# ZMIANA NAZWY FOLDERU Z TEMP NA FOLDER Z DATA
		if ls -1qA /mnt/sda1/ | grep -q .
		then
			echo "Sumy sa identyczne. Przeniesienie zdjec z tempa do glownego folderu"
			sudo sshpass -p '123qaz123qaz' ssh -o StrictHostKeyChecking=no zdjecia@192.168.0.108 mv temp_a `echo $nazwa_folderu_a | cut -b 7-` </dev/null
		else
			echo "Karta SD jest pusta"
			sudo sshpass -p '123qaz123qaz' ssh -o StrictHostKeyChecking=no zdjecia@192.168.0.108 rm -r temp_a </dev/null
		fi
		sudo umount /mnt/sda1
		sudo umount /dev/sda1
		sudo mkfs.vfat -I /dev/sda1 -n `echo $label_a | cut -b 7-`
		sudo rm -r /mnt/sda1
		exit 1
	else 
		echo "Blad, sumy sa inne"
		sudo umount /mnt/sda1
		sudo rm -r /mnt/sda1
		sudo sshpass -p '123qaz123qaz' ssh -o StrictHostKeyChecking=no zdjecia@192.168.0.108 rm -r temp_a </dev/null
		exit 1
	fi
else
	echo "Blad"
	sudo umount /mnt/sda1
	sudo rm -r /mnt/sda1
	sudo sshpass -p '123qaz123qaz' ssh -o StrictHostKeyChecking=no zdjecia@192.168.0.108 rm -r temp_a </dev/null
	exit 1
fi
