#!/bin/bash
# Program

# ODMONTOWANIE KARTY SD JESLI NADAL WIDOCZNA W SYSTEMIE
if df | grep -q '/mnt/sdc1' # Sprawdzenie czy jest zamontowane
then
	sudo umount /mnt/sdc1
	sudo rm -r /mnt/sdc1
fi

# CZYSZCZENIE ZMIENNYCH
suma1_c=""
suma2_c=""
data_c=""
label_c=""
nazwa_folderu_c=""

# CZYTANIE FOLDERU GLOWNEGO NA ZDJECIA
#
sciezka="$(cat /home/pi/Desktop/Zgrywanie_SD/sciezka)"
#sciezka=$(cat /mnt/test/foto/do_edycji)

# TWORZENIE NAZWY FOLDERU NA PODSTAWIE LABELA KARTY I AKTUALNEJ DATY
label_c=`sudo lsblk -o LABEL /dev/sdc1`
data_c=$(date +%Y-%m-%d_%H%M%S)
nazwa_folderu_c=${label_c}_${data_c}

# ZAMONTOWANIE KARTY SD
sudo mkdir /mnt/sdc1
sudo mount /dev/sdc1 /mnt/sdc1

# SPRAWDZENIE NAZWY FOLDERU
echo $nazwa_folderu_c

# SZUKANIE ZDJEC W FOLDERACH I OKRESLENIE SUMY KONTROLNEJ
suma1_c=$(sudo find /mnt/sdc1 -iname "*.*" -exec md5sum {} + | awk '{print $1}' | sort | md5sum)
echo "Zamontowano sda1"

#sudo mogrify -resize '1600x1200' /mnt/sdb1/*.*
#echo "Zmniejszono zdjecia"

# TWORZENIE FOLDERU TYMCZASOWEGO ZE ZDJECIAMI PRZENIESIONYMI Z KARTY
sudo sshpass -p '123qaz123qaz' ssh -o StrictHostKeyChecking=no zdjecia@192.168.0.108 mkdir -p temp_c </dev/null
echo "Utworzono tempa"

# WYSYLANIE ZDJEC DO FOLDERU TYMCZASOWEGO
sudo sshpass -p '123qaz123qaz' scp -o StrictHostKeyChecking=no -p $(find /mnt/sdc1 -iname "*.*") zdjecia@192.168.0.108:temp_c </dev/null
echo "Wyslano zdjecia do tempa"

# OKRESLENIE SUMY KONTROLNEJ PRZENIESIONYCH ZDJEC
suma2_c=$(sudo sshpass -p '123qaz123qaz' ssh zdjecia@192.168.0.108 find temp_c -iname "*.*" -exec md5sum {} + | awk '{print $1}' | sort | md5sum) </dev/null

# WYSWIETLENIE SUM KONTROLNYCH
echo "Stworzono sume dla *ow w tempie"
echo "Sumy:"
echo $suma1_c
echo $suma2_c

# POROWNANIE SUM KONTROLNYCH W CELU SPRAWDZENIA POPRAWNOSCI SKOPIOWANIA ZDJEC Z KARTY
if df | grep -q '/dev/sdc1'
then
	if [ "$suma1_c" = "$suma2_c" ]
	then
		# ZMIANA NAZWY FOLDERU Z TEMP NA FOLDER Z DATA
		if ls -1qA /mnt/sdc1/ | grep -q .
		then
			echo "Sumy sa identyczne. Przeniesienie zdjec z tempa do glownego folderu"
			sudo sshpass -p '123qaz123qaz' ssh -o StrictHostKeyChecking=no zdjecia@192.168.0.108 mv temp_c `echo $nazwa_folderu_c | cut -b 7-` </dev/null
		else
			echo "Karta SD jest pusta"
			sudo sshpass -p '123qaz123qaz' ssh -o StrictHostKeyChecking=no zdjecia@192.168.0.108 rm -r temp_c </dev/null
		fi
		sudo umount /mnt/sdc1
		sudo umount /dev/sdc1
		sudo mkfs.vfat -I /dev/sdc1 -n `echo $label_c | cut -b 7-`
		sudo rm -r /mnt/sdc1
		exit 1
	else 
		echo "Blad, sumy sa inne"
		sudo umount /mnt/sdc1
		sudo rm -r /mnt/sdc1
		sudo sshpass -p '123qaz123qaz' ssh -o StrictHostKeyChecking=no zdjecia@192.168.0.108 rm -r temp_c </dev/null
		exit 1
	fi
else
	echo "Blad"
	sudo umount /mnt/sdc1
	sudo rm -r /mnt/sdc1
	sudo sshpass -p '123qaz123qaz' ssh -o StrictHostKeyChecking=no zdjecia@192.168.0.108 rm -r temp_c </dev/null
	exit 1
fi
